package Interface;

import Domain.Maze;

import javax.swing.JOptionPane;

public class Visual extends javax.swing.JFrame implements Runnable {

    public int min = 0, seg = 0;
    int[][] matrizGenaral;
    Maze maze = new Maze(matrizGenaral);


    /**
     * Creates new form prueba
     */
    Thread hilo;

    public Visual() {
        initComponents();

        this.setLocationRelativeTo(null);

        hilo = new Thread(this);

        lienzo2.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        lbCronometro = new javax.swing.JLabel();
        lb_tiempo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lienzo2 = new Interface.lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Jmi_Hard = new javax.swing.JMenuItem();
        Jmi_Intermedium = new javax.swing.JMenuItem();
        Jmi_Easy = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("JFreame"); // NOI18N

        lbCronometro.setText("Cronometro");

        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1194, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        jMenu1.setText("Difficulty");

        Jmi_Hard.setText("Hard");
        Jmi_Hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmi_HardActionPerformed(evt);
            }
        });
        jMenu1.add(Jmi_Hard);

        Jmi_Intermedium.setText("Intermedium");
        Jmi_Intermedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmi_IntermediumActionPerformed(evt);
            }
        });
        jMenu1.add(Jmi_Intermedium);

        Jmi_Easy.setText("Easy");
        Jmi_Easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jmi_EasyActionPerformed(evt);
            }
        });
        jMenu1.add(Jmi_Easy);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("System");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lienzo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(lbCronometro))
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(lbCronometro)
                .addGap(40, 40, 40)
                .addComponent(lb_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lienzo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //    lienzo2.threadFast.start();

             lienzo2.maze.setF(2);
            hilo.start();
            //    lienzo2.threadItem.start();
            lienzo2.threadSmart.start();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ocurrio un error=" + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Jmi_HardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmi_HardActionPerformed
        lienzo2.setVisible(true);
        // lienzo2.threadFast.stop();
        lienzo2.dificult();
        // lienzo2.threadItem.stop();
        //   lienzo2.threadSmart.stop();
        jButton1.setEnabled(true);
        hilo = new Thread(this);
        min = 0;
        seg = 0;
        lb_tiempo.setText(min + " min: " + seg + " seg: ");
    }//GEN-LAST:event_Jmi_HardActionPerformed

    private void Jmi_IntermediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmi_IntermediumActionPerformed
        lienzo2.setVisible(true);
//        lienzo2.threadFast.stop();
//        lienzo2.threadItem.stop();
        //     lienzo2.threadSmart.stop();
        Thread smart = new Thread();
        smart.start();

        lienzo2.medium();
        jButton1.setEnabled(true);
        hilo = new Thread(this);
        min = 0;
        seg = 0;
        lb_tiempo.setText(min + " min: " + seg + " seg: ");
    }//GEN-LAST:event_Jmi_IntermediumActionPerformed

    private void Jmi_EasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jmi_EasyActionPerformed
        lienzo2.setVisible(true);
//        lienzo2.threadFast.stop();
//        lienzo2.threadItem.stop();
        lienzo2.threadSmart.stop();

        lienzo2.facil();
        jButton1.setEnabled(true);
        hilo = new Thread(this);
        min = 0;
        seg = 0;
        lb_tiempo.setText(min + " min: " + seg + " seg: ");
    }//GEN-LAST:event_Jmi_EasyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    @Override
    public void run() {
        while (true) {
            try {
                Thread.sleep(999);
                seg++;
                if (seg >= 59) {
                    min++;
                    seg = 0;
                }
                lb_tiempo.setText(min + " min: " + seg + " seg ");
                if (lienzo2.maze.getTermino() == 1) {
                    hilo.stop();
                }
            } catch (Exception e) {
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Jmi_Easy;
    private javax.swing.JMenuItem Jmi_Hard;
    private javax.swing.JMenuItem Jmi_Intermedium;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lbCronometro;
    private javax.swing.JLabel lb_tiempo;
    private Interface.lienzo lienzo2;
    // End of variables declaration//GEN-END:variables

}
